name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Start Sendria
        uses: upgundecha/start-sendria-github-action@v1.0.0

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 5.0.6

      - name: Start server
        run: |
          cd server
          npm install dotenv
          npm install
          node server.js &

      - name: Start website
        run: |
         npm install
         npm start &
      
      - name: Cypress run
        uses: cypress-io/github-action@v2

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos